# Generated by Django 3.2.5 on 2021-11-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tscore_japanese', models.IntegerField(verbose_name='国語 ')),
                ('tscore_math', models.IntegerField(verbose_name='数学 ')),
                ('tscore_english', models.IntegerField(verbose_name='英語 ')),
                ('tscore_science', models.IntegerField(verbose_name='理科 ')),
                ('tscore_social_studies', models.IntegerField(verbose_name='社会 ')),
                ('tscore_overall', models.IntegerField(verbose_name='総合 ')),
                ('rank_japanese', models.IntegerField(verbose_name='国語 ')),
                ('rank_math', models.IntegerField(verbose_name='数学 ')),
                ('rank_english', models.IntegerField(verbose_name='英語 ')),
                ('rank_science', models.IntegerField(verbose_name='理科 ')),
                ('rank_social_studies', models.IntegerField(verbose_name='社会 ')),
                ('rank_overall', models.IntegerField(verbose_name='総合 ')),
                ('date', models.DateField(verbose_name='日時 ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10, verbose_name='教科')),
                ('time', models.CharField(max_length=10, verbose_name='分')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='問題')),
                ('text', models.TextField(verbose_name='答え')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=30, verbose_name='お名前')),
                ('text', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.post', verbose_name='紐づく記事')),
            ],
        ),
    ]
