# Generated by Django 3.2.5 on 2021-11-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='rank_english',
            field=models.IntegerField(verbose_name='rank英語 '),
        ),
        migrations.AlterField(
            model_name='test',
            name='rank_japanese',
            field=models.IntegerField(verbose_name='rank国語 '),
        ),
        migrations.AlterField(
            model_name='test',
            name='rank_math',
            field=models.IntegerField(verbose_name='rank数学 '),
        ),
        migrations.AlterField(
            model_name='test',
            name='rank_overall',
            field=models.IntegerField(verbose_name='rank総合 '),
        ),
        migrations.AlterField(
            model_name='test',
            name='rank_science',
            field=models.IntegerField(verbose_name='rank理科 '),
        ),
        migrations.AlterField(
            model_name='test',
            name='rank_social_studies',
            field=models.IntegerField(verbose_name='rank社会 '),
        ),
    ]
